### PR TITLE
Update to 0.3.0

### PR DESCRIPTION
**Pull request by IngwiePhoenix**
This update includes:
- Feature to set the `Expires` header.
- Feature to set the `Cache-control` header.
- Feature to watch files for them to have changed.
  - This requires your browser to send both, `If-not-modified` and `If-none-match`.
  - This method also only works on actual files. Example: Use the original file as key, but deliver optimized file. If file changed, re-optimize.
- Feature to easily check for a changed file.
- Tests
- Documentation
- README enhancements to show new methods
- `package.json` shows correct version, but original Github repo - not my fork.

---

Voila. :) I just really need this module, so here you have a fully documented source plus new functions!

### CODE REVIEW

**Comment by IngwiePhoenix** [comment]
Oh BTW, don't forget - the version is bumped. So when you are done with merging, updating the version on NPM would be nice. :)

**Comment by taxilian** [comment]
Huh.  somehow I totally didn't see this 'til now.  Sorry about that! I'll publish it.

**Comment by IngwiePhoenix** [comment]
Thanks! I almost thought this project got abandoned or something o.o

**Comment by taxilian** [comment]
well, to be perfectly honest I had completely forgotten that I published this... =] it's just sorta been working in the one project I'm using it for and I haven't even thought about it.  I logged into npm today to look at a different project of mine (sendresponse) because I need to push an update to it and I noticed this project, checked the github repo, and saw the pull request.  I thought it was kinda funny because I literally had forgotten that I wrote this, even though I'm still using it =]

I'd be happy to give you npm publish access if you want to help keep it going; I'm not always very good at maintaining things like this

**Pull request merged**
